---
title: Elevation Tags
slug: /blog/elevationMarker
---

<figure class="video_container">
  <iframe src="https://player.vimeo.com/video/72453742?h=07b1da32c1&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="LightBoxes"></iframe>
</figure>



# Delete Empty Elevation Markers in Dynamo with Python
In this video I show how to use teh Revit API to select, filter and dleete elevation markers that do not have associated views.

## Code
 Here is the Python to get the Markers that have no Elevation on them.

```Python
# Default imports
import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

#The input to this node will be stored in the IN[0] variable and unwrap element
elements = UnwrapElement(IN[0])

#variables
output = []
elemsNotElevation = []
elemsHasElevation = []

#iterate through list and sort
for e in elements:
if e.HasElevations() == False:
elemsNotElevation.append(e)
else:
elemsHasElevation.append(e)

#compile output
output.append(elemsNotElevation)
output.append(elemsHasElevation)

#Assign your output to the OUT variable
OUT = output
```